### ISSUE TITLE
Inconsistent failures from bootstrapper test

### ISSUE THREAD

**Issue by agc93** [agc93/generator-cake#4]
The bootstrapper test in `test/bootstrapper.js` sometimes fails for no apparent reason:

```text
38 passing (2s)
1 failing
1) generator-cake:bootstrapper when enabling download creates the bootstrappers:
    AssertionError: build.ps1, no such file or directory
    + expected - actual
    -false
    +true
    
    at node_modules\yeoman-assert\index.js:64:12
    at Array.forEach (native)
    at Function.assert.file (node_modules\yeoman-assert\index.js:62:26)
    at Context.created (test\common.js:26:14)
```

I can't see any sign of why this is happening, but is reliable-ish on Travis and VSTS and can be triggered locally by running repeatedly:

```bash
npm test && npm test && npm test && npm test && npm test
```

**Comment by agc93** [comment]
Seems like the change to `got` in [33de659](https://github.com/agc93/generator-cake/commit/33de659db17209aec783975efa3e0d04b75c36e4) seems to have fixed it, so likely a problem inside `yeoman-remote`
